package avionskakompanija;
// Generated 31-Aug-2017 20:37:18 by Hibernate Tools 4.3.1



/**
 * Avion generated by hbm2java
 */
public class Avion  implements java.io.Serializable {


     private Integer idAvion;
     private String naziv;
     private String proizvodjac;
     private String tipAviona;
     private int vlasnik;
     private int kapacitet;
     private float duzina;
     private float brzina;

    public Avion() {
    }

    public Avion(String naziv, String proizvodjac, String tipAviona, int vlasnik, int kapacitet, float duzina, float brzina) {
       this.naziv = naziv;
       this.proizvodjac = proizvodjac;
       this.tipAviona = tipAviona;
       this.vlasnik = vlasnik;
       this.kapacitet = kapacitet;
       this.duzina = duzina;
       this.brzina = brzina;
    }
   
    public Integer getIdAvion() {
        return this.idAvion;
    }
    
    public void setIdAvion(Integer idAvion) {
        this.idAvion = idAvion;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getProizvodjac() {
        return this.proizvodjac;
    }
    
    public void setProizvodjac(String proizvodjac) {
        this.proizvodjac = proizvodjac;
    }
    public String getTipAviona() {
        return this.tipAviona;
    }
    
    public void setTipAviona(String tipAviona) {
        this.tipAviona = tipAviona;
    }
    public int getVlasnik() {
        return this.vlasnik;
    }
    
    public void setVlasnik(int vlasnik) {
        this.vlasnik = vlasnik;
    }
    public int getKapacitet() {
        return this.kapacitet;
    }
    
    public void setKapacitet(int kapacitet) {
        this.kapacitet = kapacitet;
    }
    public float getDuzina() {
        return this.duzina;
    }
    
    public void setDuzina(float duzina) {
        this.duzina = duzina;
    }
    public float getBrzina() {
        return this.brzina;
    }
    
    public void setBrzina(float brzina) {
        this.brzina = brzina;
    }




}


