package avionskakompanija;
// Generated 31-Aug-2017 20:37:18 by Hibernate Tools 4.3.1



/**
 * Avionskakompanija generated by hbm2java
 */
public class Avionskakompanija  implements java.io.Serializable {


     private Integer idAvioKompanije;
     private String naziv;
     private String adresa;
     private String zemlja;
     private String vebSajt;
     private String email;

    public Avionskakompanija() {
    }

    public Avionskakompanija(String naziv, String adresa, String zemlja, String vebSajt, String email) {
       this.naziv = naziv;
       this.adresa = adresa;
       this.zemlja = zemlja;
       this.vebSajt = vebSajt;
       this.email = email;
    }
   
    public Integer getIdAvioKompanije() {
        return this.idAvioKompanije;
    }
    
    public void setIdAvioKompanije(Integer idAvioKompanije) {
        this.idAvioKompanije = idAvioKompanije;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }
    public String getZemlja() {
        return this.zemlja;
    }
    
    public void setZemlja(String zemlja) {
        this.zemlja = zemlja;
    }
    public String getVebSajt() {
        return this.vebSajt;
    }
    
    public void setVebSajt(String vebSajt) {
        this.vebSajt = vebSajt;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


