package avionskakompanija;
// Generated 31-Aug-2017 20:37:18 by Hibernate Tools 4.3.1



/**
 * Gateterminal generated by hbm2java
 */
public class Gateterminal  implements java.io.Serializable {


     private Integer idGateTerminal;
     private int idAerodrom;
     private String gate;
     private String terminal;

    public Gateterminal() {
    }

    public Gateterminal(int idAerodrom, String gate, String terminal) {
       this.idAerodrom = idAerodrom;
       this.gate = gate;
       this.terminal = terminal;
    }
   
    public Integer getIdGateTerminal() {
        return this.idGateTerminal;
    }
    
    public void setIdGateTerminal(Integer idGateTerminal) {
        this.idGateTerminal = idGateTerminal;
    }
    public int getIdAerodrom() {
        return this.idAerodrom;
    }
    
    public void setIdAerodrom(int idAerodrom) {
        this.idAerodrom = idAerodrom;
    }
    public String getGate() {
        return this.gate;
    }
    
    public void setGate(String gate) {
        this.gate = gate;
    }
    public String getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }




}


