package avionskakompanija;
// Generated 31-Aug-2017 20:37:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private Integer idKorisnik;
     private String ime;
     private String prezime;
     private char pol;
     private Date datumRodjenja;
     private String email;
     private int avioKompanija;
     private String username;
     private String lozinka;
     private String tip;
     private boolean status;

    public Korisnik() {
    }

    public Korisnik(String ime, String prezime, char pol, Date datumRodjenja, String email, int avioKompanija, String username, String lozinka, String tip, boolean status) {
       this.ime = ime;
       this.prezime = prezime;
       this.pol = pol;
       this.datumRodjenja = datumRodjenja;
       this.email = email;
       this.avioKompanija = avioKompanija;
       this.username = username;
       this.lozinka = lozinka;
       this.tip = tip;
       this.status = status;
    }
   
    public Integer getIdKorisnik() {
        return this.idKorisnik;
    }
    
    public void setIdKorisnik(Integer idKorisnik) {
        this.idKorisnik = idKorisnik;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public char getPol() {
        return this.pol;
    }
    
    public void setPol(char pol) {
        this.pol = pol;
    }
    public Date getDatumRodjenja() {
        return this.datumRodjenja;
    }
    
    public void setDatumRodjenja(Date datumRodjenja) {
        this.datumRodjenja = datumRodjenja;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getAvioKompanija() {
        return this.avioKompanija;
    }
    
    public void setAvioKompanija(int avioKompanija) {
        this.avioKompanija = avioKompanija;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


