package avionskakompanija;
// Generated 31-Aug-2017 20:37:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Let generated by hbm2java
 */
public class Let  implements java.io.Serializable {


     private Integer idLet;
     private int idAerodrom1;
     private int idAerodrom2;
     private String brojLeta;
     private int idAviona;
     private String trajanjeLeta;
     private Date datumPoletanja;
     private Date vremePoletanja;
     private Date planiranoVremeDolaskaNaDes;
     private Date ocekivanoVremeDolaskaNaDes;
     private String status;
     private boolean charter;
     private Date stvarnoVremePoletanja;
     private Date stvDatumPol;
     private String dterm;
     private String dgate;
     private String attTerm;
     private String attGate;
     private Integer air;

    public Let() {
    }

	
    public Let(int idAerodrom1, int idAerodrom2, String brojLeta, int idAviona, String trajanjeLeta, Date datumPoletanja, Date vremePoletanja, Date planiranoVremeDolaskaNaDes, Date ocekivanoVremeDolaskaNaDes, String status, boolean charter, Date stvarnoVremePoletanja, Date stvDatumPol, String dterm, String dgate, String attTerm, String attGate) {
        this.idAerodrom1 = idAerodrom1;
        this.idAerodrom2 = idAerodrom2;
        this.brojLeta = brojLeta;
        this.idAviona = idAviona;
        this.trajanjeLeta = trajanjeLeta;
        this.datumPoletanja = datumPoletanja;
        this.vremePoletanja = vremePoletanja;
        this.planiranoVremeDolaskaNaDes = planiranoVremeDolaskaNaDes;
        this.ocekivanoVremeDolaskaNaDes = ocekivanoVremeDolaskaNaDes;
        this.status = status;
        this.charter = charter;
        this.stvarnoVremePoletanja = stvarnoVremePoletanja;
        this.stvDatumPol = stvDatumPol;
        this.dterm = dterm;
        this.dgate = dgate;
        this.attTerm = attTerm;
        this.attGate = attGate;
    }
    public Let(int idAerodrom1, int idAerodrom2, String brojLeta, int idAviona, String trajanjeLeta, Date datumPoletanja, Date vremePoletanja, Date planiranoVremeDolaskaNaDes, Date ocekivanoVremeDolaskaNaDes, String status, boolean charter, Date stvarnoVremePoletanja, Date stvDatumPol, String dterm, String dgate, String attTerm, String attGate, Integer air) {
       this.idAerodrom1 = idAerodrom1;
       this.idAerodrom2 = idAerodrom2;
       this.brojLeta = brojLeta;
       this.idAviona = idAviona;
       this.trajanjeLeta = trajanjeLeta;
       this.datumPoletanja = datumPoletanja;
       this.vremePoletanja = vremePoletanja;
       this.planiranoVremeDolaskaNaDes = planiranoVremeDolaskaNaDes;
       this.ocekivanoVremeDolaskaNaDes = ocekivanoVremeDolaskaNaDes;
       this.status = status;
       this.charter = charter;
       this.stvarnoVremePoletanja = stvarnoVremePoletanja;
       this.stvDatumPol = stvDatumPol;
       this.dterm = dterm;
       this.dgate = dgate;
       this.attTerm = attTerm;
       this.attGate = attGate;
       this.air = air;
    }
   
    public Integer getIdLet() {
        return this.idLet;
    }
    
    public void setIdLet(Integer idLet) {
        this.idLet = idLet;
    }
    public int getIdAerodrom1() {
        return this.idAerodrom1;
    }
    
    public void setIdAerodrom1(int idAerodrom1) {
        this.idAerodrom1 = idAerodrom1;
    }
    public int getIdAerodrom2() {
        return this.idAerodrom2;
    }
    
    public void setIdAerodrom2(int idAerodrom2) {
        this.idAerodrom2 = idAerodrom2;
    }
    public String getBrojLeta() {
        return this.brojLeta;
    }
    
    public void setBrojLeta(String brojLeta) {
        this.brojLeta = brojLeta;
    }
    public int getIdAviona() {
        return this.idAviona;
    }
    
    public void setIdAviona(int idAviona) {
        this.idAviona = idAviona;
    }
    public String getTrajanjeLeta() {
        return this.trajanjeLeta;
    }
    
    public void setTrajanjeLeta(String trajanjeLeta) {
        this.trajanjeLeta = trajanjeLeta;
    }
    public Date getDatumPoletanja() {
        return this.datumPoletanja;
    }
    
    public void setDatumPoletanja(Date datumPoletanja) {
        this.datumPoletanja = datumPoletanja;
    }
    public Date getVremePoletanja() {
        return this.vremePoletanja;
    }
    
    public void setVremePoletanja(Date vremePoletanja) {
        this.vremePoletanja = vremePoletanja;
    }
    public Date getPlaniranoVremeDolaskaNaDes() {
        return this.planiranoVremeDolaskaNaDes;
    }
    
    public void setPlaniranoVremeDolaskaNaDes(Date planiranoVremeDolaskaNaDes) {
        this.planiranoVremeDolaskaNaDes = planiranoVremeDolaskaNaDes;
    }
    public Date getOcekivanoVremeDolaskaNaDes() {
        return this.ocekivanoVremeDolaskaNaDes;
    }
    
    public void setOcekivanoVremeDolaskaNaDes(Date ocekivanoVremeDolaskaNaDes) {
        this.ocekivanoVremeDolaskaNaDes = ocekivanoVremeDolaskaNaDes;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public boolean isCharter() {
        return this.charter;
    }
    
    public void setCharter(boolean charter) {
        this.charter = charter;
    }
    public Date getStvarnoVremePoletanja() {
        return this.stvarnoVremePoletanja;
    }
    
    public void setStvarnoVremePoletanja(Date stvarnoVremePoletanja) {
        this.stvarnoVremePoletanja = stvarnoVremePoletanja;
    }
    public Date getStvDatumPol() {
        return this.stvDatumPol;
    }
    
    public void setStvDatumPol(Date stvDatumPol) {
        this.stvDatumPol = stvDatumPol;
    }
    public String getDterm() {
        return this.dterm;
    }
    
    public void setDterm(String dterm) {
        this.dterm = dterm;
    }
    public String getDgate() {
        return this.dgate;
    }
    
    public void setDgate(String dgate) {
        this.dgate = dgate;
    }
    public String getAttTerm() {
        return this.attTerm;
    }
    
    public void setAttTerm(String attTerm) {
        this.attTerm = attTerm;
    }
    public String getAttGate() {
        return this.attGate;
    }
    
    public void setAttGate(String attGate) {
        this.attGate = attGate;
    }
    public Integer getAir() {
        return this.air;
    }
    
    public void setAir(Integer air) {
        this.air = air;
    }




}


