package avionskakompanija;
// Generated 31-Aug-2017 20:37:18 by Hibernate Tools 4.3.1



/**
 * Letposada generated by hbm2java
 */
public class Letposada  implements java.io.Serializable {


     private Integer id;
     private int idPosada;
     private int idLet;

    public Letposada() {
    }

    public Letposada(int idPosada, int idLet) {
       this.idPosada = idPosada;
       this.idLet = idLet;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdPosada() {
        return this.idPosada;
    }
    
    public void setIdPosada(int idPosada) {
        this.idPosada = idPosada;
    }
    public int getIdLet() {
        return this.idLet;
    }
    
    public void setIdLet(int idLet) {
        this.idLet = idLet;
    }




}


