package avionskakompanija;
// Generated 31-Aug-2017 20:37:18 by Hibernate Tools 4.3.1



/**
 * Letradar generated by hbm2java
 */
public class Letradar  implements java.io.Serializable {


     private Integer id;
     private int idLet;
     private int idRadar;

    public Letradar() {
    }

    public Letradar(int idLet, int idRadar) {
       this.idLet = idLet;
       this.idRadar = idRadar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdLet() {
        return this.idLet;
    }
    
    public void setIdLet(int idLet) {
        this.idLet = idLet;
    }
    public int getIdRadar() {
        return this.idRadar;
    }
    
    public void setIdRadar(int idRadar) {
        this.idRadar = idRadar;
    }




}


